import type { Coin } from '../../types/coin'
// Illustrative fixtures, not the owner's collection or a numismatic reference.
const examples = [
  [
    'European connections',
    'Germany',
    2002,
    '2 euros',
    2,
    'EUR',
    'Bimetallic',
    'euro',
  ],
  [
    'A portrait in silver',
    'United Kingdom',
    1967,
    '1 shilling',
    1,
    'GBP',
    'Copper-nickel',
    'silver',
  ],
  [
    'Liberty in miniature',
    'United States',
    1999,
    '25 cents',
    0.25,
    'USD',
    'Copper-nickel clad',
    'silver',
  ],
  [
    'A familiar symbol',
    'Canada',
    2015,
    '1 dollar',
    1,
    'CAD',
    'Brass-plated steel',
    'gold',
  ],
  [
    'An everyday treasure',
    'France',
    2001,
    '1 euro',
    1,
    'EUR',
    'Bimetallic',
    'euro',
  ],
  [
    'Design across borders',
    'Italy',
    2002,
    '2 euros',
    2,
    'EUR',
    'Bimetallic',
    'euro',
  ],
  [
    'A moment in copper',
    'United States',
    2009,
    '1 cent',
    0.01,
    'USD',
    'Copper-plated zinc',
    'copper',
  ],
  [
    'A golden impression',
    'United Kingdom',
    2017,
    '1 pound',
    1,
    'GBP',
    'Bimetallic',
    'gold',
  ],
  [
    'Small change, long stories',
    'Japan',
    2019,
    '100 yen',
    100,
    'JPY',
    'Copper-nickel',
    'silver',
  ],
  [
    'A northern perspective',
    'Finland',
    2004,
    '2 euros',
    2,
    'EUR',
    'Bimetallic',
    'euro',
  ],
  [
    'A study in bronze',
    'Australia',
    1980,
    '1 cent',
    0.01,
    'AUD',
    'Bronze',
    'copper',
  ],
  [
    'An uncatalogued specimen',
    'Unknown issuing authority',
    null,
    null,
    null,
    null,
    null,
    'silver',
  ],
] as const
export const demoCoins: Coin[] = examples.map(
  ([name, country, year, denomination, value, unit, metal, art], i) => {
    const id = String(i + 1).padStart(3, '0')
    return {
      id,
      slug: name.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-'),
      name,
      issuing_authority: country,
      year,
      denomination,
      denomination_value: value,
      denomination_unit: unit,
      metal,
      weight_g: null,
      diameter_mm: null,
      mint: null,
      mint_mark: null,
      ruler: null,
      historical_period: 'Modern',
      obverse_description:
        'Illustrative coin artwork for layout preview. Replace this description and image with verified details of your specimen.',
      reverse_description:
        'Illustrative reverse artwork, not a photograph or an accurate reproduction.',
      historical_notes:
        'This is a demonstration record. Names, illustrations and notes show how your catalogue will look; verify all specifications before adding real specimens.',
      grade: null,
      grading_system: null,
      measurement_source: null,
      is_published: true,
      catalogued_at: '2026-01-' + String(i + 1).padStart(2, '0'),
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
      extra_attributes: {},
      coin_images: ['obverse', 'reverse'].map((side, j) => ({
        id: id + '-' + side,
        coin_id: id,
        side: side as 'obverse' | 'reverse',
        image_path: '/demo/' + art + '-' + side + '.svg',
        thumbnail_path: '/demo/' + art + '-' + side + '.svg',
        alt_text: 'Illustrative ' + side + ' artwork for ' + name,
        credit: 'Original demonstration artwork; not a specimen photograph',
        display_order: j,
      })),
      coin_references: [],
    }
  },
)
